package cmd

import (
	"path/filepath"

	"github.com/activatedio/gen"
	"github.com/dave/jennifer/jen"
)

// GeneratedBy is the source identifier in the "Code generated by ... DO NOT
// EDIT." header of every emitted file.
const GeneratedBy = "github.com/activatedio/cmdinfra"

// FileMain is the file-handler key for the spec's generated root file.
// Consumers can register additional file handlers against it (via
// Registry.WithHandlerEntries) to append code to the same file without
// forking the library.
type FileMain struct {
	Spec *Spec
}

// NewRegistry returns a gen.Registry loaded with cmdinfra's handlers. The
// consumer's gen/main.go typically calls
//
//	cmd.NewRegistry().RunDirectoryPathHandler("../generated", &cmd.Spec{...})
func NewRegistry() gen.Registry {
	return gen.NewRegistry().WithHandlerEntries(
		gen.NewHandlerEntries().
			AddDirectoryHandler(gen.NewKey[*Spec](), specDirectoryHandler).
			AddFileHandler(gen.NewKey[*FileMain](), fileMainHandler),
	)
}

// specDirectoryHandler owns the target directory. The bootstrap surface is
// a single root_gen.go; service and resource command files join it as the
// command generators land.
func specDirectoryHandler(dirPath string, r gen.Registry, entry any) {

	spec := entry.(*Spec)
	validateSpec(spec)

	gen.WithFile(spec.Package, filepath.Join(dirPath, "root_gen.go"), func(f *jen.File) {
		r.RunFileHandler(f, &FileMain{Spec: spec})
	}, gen.WithGeneratedBy(GeneratedBy))
}

func validateSpec(spec *Spec) {

	if spec.Package == "" {
		panic("cmdinfra: Spec.Package must be set")
	}
	if spec.Root.Use == "" {
		panic("cmdinfra: Spec.Root.Use must be set")
	}
}

// fileMainHandler composes the sections of the root file.
func fileMainHandler(f *jen.File, _ gen.Registry, entry any) {
	fm := entry.(*FileMain)
	writeRoot(f, fm.Spec)
}
